-- MySQL Script generated by MySQL Workbench
-- 06/14/19 22:07:55
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ProjetoTP
-- -----------------------------------------------------
CREATE DATABASE projetotp;

USE  projetotp;
-- -----------------------------------------------------
-- Schema ProjetoTP
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ProjetoTP` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `ProjetoTP` ;

-- -----------------------------------------------------
-- Table `ProjetoTP`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProjetoTP`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nm_usuario` VARCHAR(45) NOT NULL COMMENT '',
  `nm_email` VARCHAR(45) NOT NULL COMMENT '',
  `cd_senha` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`id_usuario`)  COMMENT '',
  UNIQUE INDEX `nm_email_UNIQUE` (`nm_email` ASC)  COMMENT '')
ENGINE = InnoDB;

INSERT INTO `usuario` (`id_usuario`, `nm_usuario`, `nm_email`, `cd_senha`) VALUES
(null, 'teste', 'teste@gmail.com', '123');
-- -----------------------------------------------------
-- Table `ProjetoTP`.`item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProjetoTP`.`item` (
  `id_item` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `id_usuario` INT NOT NULL COMMENT '',
  `nm_item` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`id_item`)  COMMENT '',
  INDEX `fk_lista_usuario_idx` (`id_usuario` ASC)  COMMENT '',
  CONSTRAINT `fk_lista_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `ProjetoTP`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

INSERT INTO `item` (`id_item`, `id_usuario`, `nm_item`) VALUES
(1, 1, 'item 1'),
(2, 1, 'item 2'),
(3, 1, 'item 3'),
(4, 1, 'item 4'),
(5, 1, 'item 5');

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
